---
title: 'Mariana Quintero Vecchiato'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title.html"
url: http://mqvlm.github.io/
full_name: 'Mariana Quintero Vecchiato'
first_name: 'Mariana'
last_name: 'Quintero Vecchiato'
blog_title: 'Mariana Quintero Vecchiato is an educator and digital
  literacy advocate based in Barcelona.'
author_img_name_path: "/img/users/user.jpg"
disqus_shortname: mqvlm
copyright_year: '2020'
google_analytics_code: ''
aboutme: 'Mariana Quintero Vecchiato is an educator and digital
  literacy advocate based in Barcelona.'
twitter: 
github: mqvlm
tumblr: http://memmorabilia.tumblr.com/
facebook: ''
linkined_url: ''
instagram: http://www.instagram.com/nubicola
repourl: https://github.com/mqvlm/mqvlm.github.io/tree/master/code/
